name: Build
# TODO: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Accept Licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Test
        run: ./gradlew gesturesequencetest:pixel2api29DebugAndroidTest -Pandroid.sdk.channel=3
