name: Build
# TODO: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Assemble
        run: ./gradlew gesturesequence:assembleRelease