name: PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # TODO: Run tests
      - name: Assemble
        run: ./gradlew gesturesequence:assembleRelease