name: Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

#      - name: Accept Licenses
#        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

#      - name: Test
#        run: ./gradlew gesturesequencetest:pixel2api29DebugAndroidTest

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
